[package]
name = "bingimg"
version = "0.1.0"
authors = ["root"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ureq = "2.0.1"
regex = "1"
time = "0.2.25"
mysql = "20.1.0"